//! `TokenUsage` — cross-protocol token-usage accounting.
//!
//! Split out of `llm/types.rs` (2026-08-08 batch3). Standalone 5-field struct.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// TokenUsage — A4 (Token Usage Tracking)
// ---------------------------------------------------------------------------

/// Token usage reported by the LLM at the end of one turn. Schema is
/// **protocol-agnostic** — both Anthropic (`message_delta.usage`) and
/// OpenAI (last-chunk `usage`) are normalized into this 4-field shape
/// by the provider before yielding `ChatEvent::Done`. The agent loop
/// reads `Option<TokenUsage>` from `ChatEvent::Done` and accumulates
/// it into `sessions` (per-session totals).
///
/// Field semantics (Anthropic schema — the reference):
///
/// - `input_tokens` — total input tokens for the request, **inclusive
///   of** `cache_creation_input_tokens` + `cache_read_input_tokens`.
///   This is the value displayed in the ChatInput hint as "current
///   context usage, not cumulative" (per Anthropic's statusline
///   convention; same shape as `sanztheo/claude-code-statusline`).
/// - `output_tokens` — tokens generated by the model. **Not** counted
///   as context pressure (the response is not context).
/// - `cache_creation_input_tokens` — newly created cache tokens
///   (eligible for a cache hit next turn).
/// - `cache_read_input_tokens` — cache tokens served from a prior
///   `cache_creation` (the cheap path). The Anthropic API bills
///   these at 0.1x input; OpenAI's `cached_tokens` at 0.5x.
///
/// OpenAI normalization (PR3 of multi-model):
///
/// - `prompt_tokens` → `input_tokens`
/// - `completion_tokens` → `output_tokens`
/// - `prompt_tokens_details.cached_tokens` → `cache_read_input_tokens`
/// - `cache_creation_input_tokens` → 0 (no OpenAI equivalent today)
///
/// `None` from a `ChatEvent::Done` means the provider did not (or
/// could not) report usage — typically cancel, network drop, or
/// pre-usage error. The agent loop treats `None` as "skip the
/// accumulation write" and logs at `info!`.
/// 2026-06-26 (token-usage snapshot fix): `context_input_tokens` is
/// the cross-provider-normalized "total input for this request" —
/// the single canonical numerator the frontend uses for the
/// "context usage %" hint. Provider mapping:
/// - Anthropic: `input_tokens + cache_creation_input_tokens +
///   cache_read_input_tokens` (Anthropic's `input_tokens` excludes
///   cache reads/creations; the true context footprint is the sum).
/// - OpenAI: `prompt_tokens` (already inclusive of
///   `cached_tokens`; OpenAI does not split cache creation out, so
///   no addition is needed — adding `cache_read` would double-count).
///
/// `#[serde(default)]` is required so that legacy
/// `subagent_runs.token_usage_json` rows written before this field
/// existed (4-field shape) still deserialize cleanly (`default = 0`).
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct TokenUsage {
    pub input_tokens: u32,
    pub output_tokens: u32,
    pub cache_creation_input_tokens: u32,
    pub cache_read_input_tokens: u32,
    #[serde(default)]
    pub context_input_tokens: u32,
}
